---
language: php

cache:
  directories:
    - "${HOME}/.composer/cache"
    - "${HOME}/.npm/"
env:
  global:
    - PATH="${HOME}/bin:${PATH}"

jobs:
  include:
    - php: 7.3
      name: Linting
      stage: lint
      before_install:
        - npm set loglevel error
        - npm set progress false
      install:
        - npm install -g jsonlint
      script:
        - find . -type f -name "*.json" -print0 | xargs -0 -n1 jsonlint -q
        - composer validate

    - stage: test
      php: 7.4snapshot
      allow_failures: true
    - php: 7.3
      env: SECURITY=1
    - php: 7.2
    - php: 7.1
    - php: 7.0
    - php: 5.6
    - php: 5.5
      # As the latest Debian does not support PHP 5.5 anymore, we need to force using 'trusty'.
      dist: trusty
    - php: 5.4
      # As the latest Debian does not support PHP 5.4 anymore, we need to force using 'trusty'.
      dist: trusty
    - php: 5.3
      # As the latest Debian does not support PHP 5.3 anymore, we need to force using 'precise'.
      dist: precise
      script:
        - find . -type f -name "*.php" -print0 | xargs -0 -n1 php -l
        - travis_wait composer install --no-interaction --no-progress --no-scripts --no-suggest --optimize-autoloader --prefer-dist --verbose
        - composer install-codestandards
        - ./vendor/bin/phpcs -i
        - ./vendor/bin/phpcs -s --standard=PHPCompatibility --runtime-set testVersion "${TRAVIS_PHP_VERSION:0:3}" --exclude=PHPCompatibility.Upgrade.LowPHP ./src/

  fast_finish: true

script:
  - find . -type f -name "*.php" -print0 | xargs -0 -n1 php -l
  - travis_wait composer install --no-interaction --no-progress --no-scripts --no-suggest --optimize-autoloader --prefer-dist --verbose
  - composer install-codestandards
  - ./vendor/bin/phpcs -i
  - ./vendor/bin/phpcs -s --runtime-set testVersion "${TRAVIS_PHP_VERSION:0:3}" --exclude=PHPCompatibility.Upgrade.LowPHP ./src/
  - if [[ "$SECURITY" == "1" ]];then ./vendor/bin/security-checker -n security:check --end-point=http://security.symfony.com/check_lock; fi
